#高性能主从注册中心
spring:
    application:
       name : eureka
server:
    port: 8761
security:
    basic:
        enabled: true
    user:
        name: nextTrucking
        password: test123
eureka:
    instance:
        hostname: devsvc02
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    client:
        #健康检查
        healthcheck:
            enabled: true
        #表示是否将自己注册到Eureka Server
        registerWithEureka: false
        #表示是否从Eureka Server获取注册信息，默认为true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${security.user.name}:${security.user.password}@devsvc01:${server.port}/eureka/,http://${security.user.name}:${security.user.password}@devsvc03:${server.port}/eureka/
